### ISSUE TITLE
check_mk web interface url?

### ISSUE THREAD

**Issue by zoobab** [ConSol/omd-labs-docker#1]
Hi,

Once the container is running, any idea where to go to get the check_mk web interface?

Best,

**Comment by simonmeggle** [comment]
Just set the default web GUI to _check_mk_ and turn off Thruk cookie auth.

**Comment by zoobab** [comment]
Let me make a proper fix for that issue.

**Comment by simonmeggle** [comment]
Imho there is no need for a common "fix". 

Write a [Ansible dropin](https://github.com/ConSol/omd-labs-docker#ansible-drop-ins) task to set these two parameters on startup or use [volume mounts](https://github.com/ConSol/omd-labs-docker#use-data-containers) to import the whole etc directory. 
Alternatively, you can build an own docker image which has multisite as the default GUI.
