### ISSUE TITLE
Creating a custom site doesn't work

### ISSUE THREAD

**Issue by mcasviper** [ConSol/omd-labs-docker#14]
I tried to create a custom site, but the described way
export NEW_SITENAME=CUSTOMNAME; make -f MAKEFILE build 
only builds the site demo. The correct environment is show in the first step of the build process. 
I cloned the github master today.

**Comment by simonmeggle** [comment]
Thanks for reporting this. The Makefile was wrong and the documentation unclear. 
Please try again (when bulding the base image, export the `SITENAME` variable)
