### ISSUE TITLE
High CPU load because of rsync

### ISSUE THREAD

**Issue by mcasviper** [ConSol/omd-labs-docker#15]
Hi,

we have a lot of cpu load because of the sync procs for the mounted external paths. Is it possible to mount them directly to the correct path instead of the *.mount destination? I think this would reduce the load a lot or are there any issues which i don't have in my mind?

**Comment by simonmeggle** [comment]
Mounting the dirs directly was what we tried first, but OMD highly relies on the correct permissions on that folder. Running the container on Openshift does not allow to set the directory owner.
This was the reason why we implemented the internal folder synchronisation. 
Currently lsyncd tries to sync the files as fast as possible. Perhaps it makes sense to lower the interval a little bit, but I did not have the time to test that.
