### ISSUE TITLE
Cron in container stops

### ISSUE THREAD

**Issue by alphaDev23** [ConSol/omd-labs-docker#19]
Is it expected that cron is always running?   It currently does not within the container.  

If it is expected to always be running, shouldn't there be a supervisor service included in the container to ensure that cron is always running?

**Comment by sni** [comment]
yes, cron is expected to always run. Does it crash or doesn't it start correctly?

**Comment by alphaDev23** [comment]
It starts and remains running.  The issue may be related to the fact that we snapshot the VM upon which the container resides daily.  Other services in the OMD container remain running but cron remains down.

Have you considered including a supervisor in the container given that there is more service implemented?

**Comment by sni** [comment]
i have no idea what you are doing, but if you talk about the cron service in OMD, then this is kind of a special service. It does not relate to a specific process, but load the cron entries from `~/etc/cron.d` into the users crontab. `omd stop crontab` simply does a `crontab -r`.

**Comment by alphaDev23** [comment]
Regardless of why cron is stopping, it is stopping and there appears to be no automated mechanism to restart it.  Since you mentioned above that cron should always run (I interpret this to mean that the result of 'docker exec -it <OMD container name> service cron status' should always be 'cron is running') and it is not always running (results in 'cron is not running'), the 'local/omd-labs-ubuntu' image is not engineered correctly to ensure that services remain running.  A supervisor service, e.g. http://supervisord.org, would resolve this issue.

Please let me know your thoughts.

**Comment by alphaDev23** [comment]
Any update on this?

**Comment by sni** [comment]
there are no plans to add this feature in the near future. But you could always create your own container with additional features.

**Comment by alphaDev23** [comment]
Interesting response and reaction to a bug in which a simple solution exits.
