### ISSUE TITLE
How do I log in?

### ISSUE THREAD

**Issue by dmp1ce** [ConSol/omd-labs-docker#20]
I have started the [docker image](https://hub.docker.com/r/consol/omd-labs-ubuntu) and have navigated to the demo site but I cannot figure out how to log in. I found[ documentation on paying attention to the password generated](https://labs.consol.de/omd/getting_started.html) but I didn't see where a password was generated.

Can you help me log in?

**Comment by dmp1ce** [comment]
I figured out a way to log in. After starting up the container I did the following:

```
docker-compose exec monitor bash
omd su demo
cd etc
htpasswd htpasswd omdadmin
```

Is this how the image is expected to be used? Perhaps I should use my own Docker image based on this one?

**Comment by sni** [comment]
There is not _that_ single way how to use this container. I usually have a Dockerfile based on this container where i add ansible playbooks to setup the site.

ex.: https://github.com/sni/Thruk/blob/master/t/scenarios/rest_api/omd/Dockerfile
Then i set the admin password here:
https://github.com/sni/Thruk/blob/master/t/scenarios/rest_api/omd/playbook.yml#L4

Maybe we add a environment variable to set the initial password in the future, but its not there yet.
I added a small section to the readmin with 826d2f88 to make things a bit clearer for now.

**Comment by dmp1ce** [comment]
Sorry for the basic questions. I am assuming the way to configure nagios is with check_mk using the `cmk` tool and check_mk web interface. However, I'm not sure how to log into the check_mk webservice. The documentation seems to suggest that the password is managed by the `htpasswd` file but changing it didn't help me log in. https://mathias-kettner.com/cms_introduction_packages.html

How do I log into check_mk?

**Comment by dmp1ce** [comment]
I just found https://github.com/ConSol/omd/issues/75 and https://github.com/ConSol/omd/issues/74

I'm just trying to get started with OMD using this docker image. Where would I go to get started with something basic like adding hosts? I am familiar with Nagios configurations, I just don't know if OMD is intended to manually edit config files or if they are generated by something.

**Comment by dmp1ce** [comment]
OK. I think I found what I was looking for. At the bottom left of the Thruk web interface there is a "Config tool" link. That page has the tools to create new hosts, verify that the changes are correct and apply the changes.

Maybe my rubber duck debugging will be helpful to someone else too. 🦆
