### ISSUE TITLE
Config tool does not restart naemon core

### ISSUE THREAD

**Issue by dmp1ce** [ConSol/omd-labs-docker#22]
When applying config changes through the config tool GUI in Thruk, the restart of the naemon core times out. The resulting output is:

```

Command Output:
--
Reloading naemon configuration (PID: 421)... Stopping naemon........................................................................................................................... sending SIGKILL....................ERROR Unable to stop naemon. Terminating... Starting naemon...OK  Reloading naemon configuration (PID: 421)... Stopping  naemon........................................................................................................................... sending SIGKILL....................ERROR Unable to stop naemon. Terminating... Starting naemon...OK Warning: waiting for core reload failed.
```

I have to resort to a `docker-compose restart` on the command line to apply configuration changes.

**Comment by dmp1ce** [comment]
Perhaps a `SIGHUP` would be more appropriate for if the process cannot be restarted but I'm not sure if `SIGKILL` is hard coded into Thruk.

**Comment by sni** [comment]
none of that is hardcoded in Thruk, you can set the `obj_reload_cmd` command from the backend section. See 
https://thruk.org/documentation/configuration.html#_component-thruk-backend
for more details.
You have to copy the Backend section from the `thruk.conf` into your `thruk_local.conf` first. You can then use whatever command you like.

**Comment by dmp1ce** [comment]
I still wonder if this might be an valid issue for the Docker configuration because the default fails.

**Comment by sni** [comment]
I can reproduce it with the :latest tag but not with the :nightly. So i assume its already fixed and will be ok with the next release.
