### ISSUE TITLE
Starting / restarting site in running container fails mounting tmpfs (debian, ubuntu)

### ISSUE THREAD

**Issue by kshepherd** [ConSol/omd-labs-docker#24]
I'm having trouble in Docker with the tmpfs mount step that happens in startup... this happens with omd-labs-docker and has happened in my own local customer Docker container that I was using to install OMD from scratch. The started container will report all OK with running OMD services, but after stopping in the running container, I can't start or restart without encountering a mount error at the temporary filesystem step. This (at least partially) breaks my restore.

```
Executing post-update script "thruk"...OK
Finished update to version 4.60-labs-edition.
Creating temporary filesystem /omd/sites/examplesite/tmp...mount: /opt/omd/sites/examplesite/tmp: permission denied.
ERROR
```

fstab looks like this:
```
# UNCONFIGURED FSTAB FOR BASE SYSTEM
tmpfs  /omd/sites/examplesite/tmp tmpfs noauto,user,mode=755,uid=examplesite,gid=examplesite 0 0
```
Not sure if this is something I'm missing, or a bug. I've tried on a few different Ubuntu host systems, using both debian and ubuntu makefiles.

In the example here, I'm trying to restore an older (2.4) OMD backup. The upgrade appears to work well, but I get the mount error, and none of the backup's *.cfg objects end up in my running site. Same error occurs when starting or restarting form a running container, though services seem ok at initial container startup.

**Comment by sni** [comment]
TMPFS must be disabled when using OMD with docker. This is the default when you start from scratch but it might be enabled if you import an existing site from a non-docker installation.
Simply run `omd config set TMPFS off`.

**Comment by kshepherd** [comment]
Thanks @sni . I'd gone as far as modifying the backup to disable tmpfs in its own site.conf, and trying to make sure the same is set in my own, but... it didn't seem to help. I hadn't tried the command itself though, so I'll give that a go. And perhaps if I can temporarily disable on the source server before doing a backup, that'll be a less hacky way of turning it off in the migration data. Otherwise it might help if the restore and other commands need to take a `--no-tmpfs` arg like create does?
