### ISSUE TITLE
[Thruk] Can't create new bookmarks

### ISSUE THREAD

**Issue by pottah** [ConSol/omd-labs-docker#39]
Hello,

I'm not sure if the issue only appears when using the container but when trying to create a new bookmark it will fail with `Forbidden`.
It seems like that this is only the case if there is a `?` in the URL (Even if encoded `%3F`) because if I delete the `%3F` from the `?referer=` and the `?` from the actual URL that I want to use for the bookmark it will create it.

If I should open the issue at the Thruk repository please tell me so 😄 

Thanks in advance!
potter

**Comment by sni** [comment]
you don't have to, there is one already: https://github.com/sni/Thruk/discussions/1383
Also one for OMD: https://github.com/ConSol-Monitoring/omd/issues/192
In short, we are working on it and the nightly builds should be fine.
