### ISSUE TITLE
omd-labs-ubuntu: docker run fails with wrong permissions

### ISSUE THREAD

**Issue by dklueh** [ConSol/omd-labs-docker#9]
root@###:~# docker run consol/omd-labs-ubuntu
container_linux.go:247: starting container process caused "exec: \"/root/start.sh\": permission denied"
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/root/start.sh\\\": permission denied\"\n".

**Comment by simonmeggle** [comment]
Thanks, solved by abcd9914e4ef1a73fa49152625e7bef8a0acc49a
